### PR TITLE
Update Package to work with latest version of the TriFinger robot software

### PR DESCRIPTION
**Pull request by luator**
# Description

Update the package so that it works with the latest version of the TriFinger robot software (as it is used in the Real Robot Challenge 2021).  The most significant change is to migrate from ROS1/catkin to ROS2/ament_python.  Apart from this, a few modifications were necessary as the API changed a bit (see the individual commits for details).

Note: I only tested by running it through the submission system setup (mostly with a simulation backend).  I saw that there are other scripts for running locally, which probably need to be adjusted as well.  Further the README hasn't been updated yet.

You can get the latest base Singularity image via

    singularity pull library://felix.widmaier/trifinger/user:latest

I don't know if you actually want to merge this or if you prefer to keep it in a separate branch but I think in any case using a pull request is the easiest way to review the changes.

# How I Tested
By executing with the submission system setup, testing the following combinations:

    {mp-pg, cic-cg, cpc-tg} x {<none>, --residual, --bo} x {level 3, level 4}

I only did a few tests with mp-pg on the real robot, the rest was tested using a simulated robot backend to safe time.
I only tested if the code was running without error and if the robot was doing something.  I didn't compare to the behaviour before the changes, so I cannot say if it behaves the same way.
Note that the behaviour in simulation has most likely changed, because the simulation parameters have changed (using more accurate inertia values now).

# TODO

- [ ] Update other scripts apart from `run_episode.py` if needed.
- [x] Update README

### CODE REVIEW

**Comment by cbschaff** [comment]
Hey Felix!

Thanks for doing this update. I updated the run_locally.sh script to build the ros2 packages, but I ran into an error when trying to run our code in simulation. Do you know what in the API might have changed to cause this error?

Here are the steps to reproduce the bug:

1) build the singularity image using image.def
2) run the command `./run_locally.sh ./image.sif ros2 run rrc run_local_episode.py 4 mp-pg`

This should produce the trace:
```
Traceback (most recent call last):
  File "/ws/install/rrc/lib/rrc/run_local_episode.py", line 61, in <module>
    main()
  File "/ws/install/rrc/lib/rrc/run_local_episode.py", line 51, in main
    obs = env.reset()
  File "/ws/install/rrc/lib/python3.8/site-packages/env/wrappers.py", line 283, in reset
    obs = self.env.reset(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gym/core.py", line 237, in reset
    return self.env.reset(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gym/core.py", line 264, in reset
    observation = self.env.reset(**kwargs)
  File "/ws/install/rrc/lib/python3.8/site-packages/env/cube_env.py", line 302, in reset
    self.prev_observation, _, _, _ = self.step(self.initial_action)
  File "/ws/install/rrc/lib/python3.8/site-packages/env/cube_env.py", line 235, in step
    t = self.platform.append_desired_action(robot_action)
  File "/opt/blmc_ei/install/trifinger_simulation/lib/python3.8/site-packages/trifinger_simulation/trifinger_platform.py", line 299, in append_desired_action
    self._action_log["actions"].append(copy.deepcopy(log_entry))
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'robot_interfaces.py_trifinger_types.Action' object
```

Do you have some insight into what is going on here?

**Comment by luator** [comment]
@cbschaff There is now a deepcopy of the action happening at some place in `TriFingerPlatform`.  It seems I only tested this with actions of type `trifinger_simulation.action.Action` but not with `robot_interfaces.trifinger.Action`.  For the latter it fails because C++ types bound with pybind11 are not deepcopy-able by default.

I think the proper solution to this is to add pickle-support (and thus implicitly deepcopy-support) to these bound types.  I'll look into this, but for the meantime, there is a simple workaround.  Add the following lines in cube_env.py to make `Action` deepcopy-able:

``` python
import copy

def action_deepcopy(self, memo):
    cls = self.__class__
    cpy = cls.__new__(cls)
    memo[id(self)] = cpy

    cpy.torque = copy.deepcopy(self.torque, memo)
    cpy.position = copy.deepcopy(self.position, memo)
    cpy.position_kp = copy.deepcopy(self.position_kp, memo)
    cpy.position_kd = copy.deepcopy(self.position_kd, memo)

    return cpy

robot_interfaces.trifinger.Action.__deepcopy__ = action_deepcopy
```

**Comment by cbschaff** [comment]
Thanks Felix. I pushed the workaround. Everything now runs in simulation, but the behavior is different enough that I think we should keep this in its own branch.

@madan96 @nifunk cpc and cic now seem to get stuck in loops in the state machine and fail to even grasp the cube in simulation. If you have time, could you look into why this is the case? No need to match the behavior of the main branch, but it would be nice to have something that works reasonably. 

These commands should replicate the weird behavior:
For cpc: ```./run_locally.sh image.sif ros2 run rrc run_local_episode.py 4 cpc-tg```
For cic: ```./run_locally.sh image.sif ros2 run rrc run_local_episode.py 4 cic-cg```

**Comment by luator** [comment]
> Everything now runs in simulation, but the behavior is different enough that I think we should keep this in its own branch.

I agree that it's probably better to keep it separate.  I assume that the difference in behaviour is mostly caused by changes on the robot model that is used in the simulation.  Link masses and inertias have been changed to be more accurate and also the meshes are new (I don't expect that the latter has a significant impact on the behaviour but who knows).

**Comment by nifunk** [comment]
Hi,
Thanks a lot already for your efforts @cbschaff and @luator. I am afraid that I will only have time after the CoRL deadline to look into this,...

**Comment by luator** [comment]
I updated the base Singularity image, so the deepcopy workaround is not needed anymore.  You can use

    singularity pull library://felix.widmaier/trifinger/user:latest

to get the latest version.

**Comment by cbschaff** [comment]
Thanks. I removed the workaround and confirmed that the code runs with the new image.

**Comment by luator** [comment]
Hi everyone, I realised that this PR is still pending.  I added a note to the README, clarifying that this is an updated version of the code that works with the current robot software but may behave a bit differently.  Does this make sense to you?

Apart from this, is there anything else that needs to be done here?

As we decided to keep it on a separate branch, it might make sense to add a comment to the README on master, pointing to this branch?  Also, should we keep the branch name "ros2" or is there a better name?

**Comment by cbschaff** [comment]
Thanks Felix. That looks good to me. I will add a note to the readme in main about this branch. 

Aside from that, I don't think anything needs to be done. When I last tested things, the code worked with the ros 2 infrastructure, but at a reduced performance in simulation.

**Comment by luator** [comment]
Thanks @cbschaff, I'll close this PR then.

**Pull request closed without merging**
